In [21]:
# Dependencies
import pandas as pd
import numpy as np
import datetime
import time
import sqlite3
# Store filepath in a variable
file_one = "db/NYPD_Shooting_Incident_Data__Historic_.csv"

In [2]:
shootings_df = pd.read_csv(file_one, encoding="ISO-8859-1")

In [3]:
shootings_df

,INCIDENT_KEY,OCCUR_DATE,OCCUR_TIME,BORO,PRECINCT,JURISDICTION_CODE,LOCATION_DESC,STATISTICAL_MURDER_FLAG,PERP_AGE_GROUP,PERP_SEX,PERP_RACE,VIC_AGE_GROUP,VIC_SEX,VIC_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude
0,169180023,09/09/2017,3:57:00,STATEN ISLAND,120,0.0,NaN,False,NaN,NaN,NaN,25-44,M,BLACK,959975,171772,40.638126,-74.087467
1,169180027,09/09/2017,22:15:00,BRONX,50,0.0,NaN,False,NaN,NaN,NaN,25-44,M,BLACK HISPANIC,1011288,255912,40.869061,-73.902242
2,169180025,09/09/2017,18:35:00,BROOKLYN,79,2.0,MULTI DWELL - PUBLIC HOUS,False,NaN,NaN,NaN,18-24,M,BLACK,999888,193014,40.696450,-73.943607
3,169180024,09/09/2017,15:20:00,BROOKLYN,67,0.0,NaN,False,18-24,M,BLACK,18-24,M,BLACK,997784,172132,40.639137,-73.951236
4,169180022,09/09/2017,0:20:00,BROOKLYN,61,2.0,MULTI DWELL - PUBLIC HOUS,False,NaN,NaN,NaN,25-44,M,ASIAN / PACIFIC ISLANDER,1001019,156467,40.596134,-73.939619
5,156603440,09/09/2016,20:58:00,BROOKLYN,67,0.0,MULTI DWELL - APT BUILD,False,25-44,M,BLACK,<18,M,BLACK,1003592,176432,40.650929,-73.930297
6,156603439,09/09/2016,20:43:00,BRONX,41,0.0,NaN,False,NaN,NaN,NaN,25-44,M,WHITE HISPANIC,1011370,235889,40.814103,-73.902027
7,156603438,09/09/2016,11:50:00,MANHATTAN,32,0.0,NaN,False,NaN,NaN,NaN,<18,M,BLACK,1001664,239682,40.824538,-73.937081
8,156552658,09/09/2016,0:18:00,QUEENS,113,0.0,NaN,False,NaN,NaN,NaN,25-44,M,BLACK,1044416,183458,40.670030,-73.783113
9,146014287,09/09/2015,23:08:00,BRONX,47,2.0,MULTI DWELL - PUBLIC HOUS,False,NaN,NaN,NaN,25-44,M,BLACK,1026323,261252,40.883658,-73.847848
10,146014286,09/09/2015,23:00:00,MANHATTAN,28,0.0,NaN,False,NaN,NaN,NaN,25-44,M,BLACK,998318,231726,40.802707,-73.949188
11,146013532,09/09/2015,19:03:00,BROOKLYN,77,0.0,NaN,True,25-44,M,BLACK,18-24,M,BLACK,1001196,185003,40.674459,-73.938910
12,145992814,09/09/2015,11:54:00,BROOKLYN,70,0.0,MULTI DWELL - APT BUILD,False,<18,M,WHITE HISPANIC,<18,M,WHITE HISPANIC,994904,167484,40.626383,-73.961621
13,138627598,09/09/2014,17:36:00,BROOKLYN,73,0.0,NaN,False,NaN,NaN,NaN,18-24,M,BLACK,1006587,182075,40.666411,-73.919485
14,92525610,09/09/2013,5:26:00,BROOKLYN,75,0.0,MULTI DWELL - PUBLIC HOUS,True,NaN,NaN,NaN,18-24,M,BLACK,1015537,178639,40.656952,-73.887239
15,92507649,09/09/2013,4:35:00,BROOKLYN,79,0.0,NaN,False,NaN,NaN,NaN,25-44,M,BLACK,995342,191876,40.693333,-73.960003
16,92507648,09/09/2013,3:55:00,MANHATTAN,17,0.0,BAR/NIGHT CLUB,False,25-44,M,BLACK,25-44,M,BLACK,991876,214311,40.754916,-73.972476
17,92525805,09/09/2013,15:14:00,QUEENS,113,0.0,NaN,False,25-44,M,BLACK,25-44,M,BLACK,1050964,189413,40.686328,-73.759450
18,86650273,09/09/2012,2:15:00,QUEENS,113,0.0,NaN,False,NaN,NaN,NaN,18-24,M,BLACK,1051505,190826,40.690203,-73.757485
19,86650272,09/09/2012,2:01:00,MANHATTAN,28,0.0,NaN,False,NaN,NaN,NaN,25-44,M,BLACK,997995,230064,40.798146,-73.950358
20,86664788,09/09/2012,23:22:00,STATEN ISLAND,120,0.0,NaN,True,25-44,M,BLACK,18-24,M,BLACK,951991,171198,40.636525,-74.116231
21,86651100,09/09/2012,15:47:00,BROOKLYN,77,0.0,NaN,False,NaN,NaN,NaN,25-44,M,BLACK,998182,186167,40.677659,-73.949773
22,80667853,09/09/2011,23:00:00,BRONX,44,0.0,NaN,False,18-24,M,BLACK,18-24,F,BLACK,1007977,246029,40.841944,-73.914249
23,80667853,09/09/2011,23:00:00,BRONX,44,0.0,NaN,False,18-24,M,WHITE HISPANIC,18-24,F,BLACK,1007977,246029,40.841944,-73.914249
24,80667853,09/09/2011,23:00:00,BRONX,44,0.0,NaN,False,18-24,M,BLACK,18-24,M,BLACK,1007977,246029,40.841944,-73.914249
25,80667853,09/09/2011,23:00:00,BRONX,44,0.0,NaN,False,18-24,M,WHITE HISPANIC,18-24,M,BLACK,1007977,246029,40.841944,-73.914249
26,80667641,09/09/2011,22:43:00,QUEENS,104,0.0,MULTI DWELL - APT BUILD,False,18-24,M,BLACK HISPANIC,<18,M,WHITE HISPANIC,1008657,195934,40.704445,-73.911973
27,80667641,09/09/2011,22:43:00,QUEENS,104,0.0,MULTI DWELL - APT BUILD,False,<18,M,BLACK HISPANIC,<18,M,WHITE HISPANIC,1008657,195934,40.704445,-73.911973
28,80655008,09/09/2011,13:32:00,BROOKLYN,67,0.0,NaN,False,NaN,NaN,NaN,18-24,M,BLACK,996921,176967,40.652409,-73.954337
29,80654704,09/09/2011,12:39:00,QUEENS,114,2.0,MULTI DWELL - PUBLIC HOUS,False,<18,M,BLACK,18-24,M,BLACK,1009725,215121,40.757105,-73.908048
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20629,173354054,01/06/2018,21:05:00,BRONX,47,0.0,MULTI DWELL - APT BUILD,False,18-24,M,BLACK,18-24,M,BLACK HISPANIC,"1,024,405","267,090",40.899691,-73.854749
20630,173354054,01/06/2018,21:05:00,BRONX,47,0.0,MULTI DWELL - APT BUILD,True,18-24,M,BLACK,18-24,M,BLACK HISPANIC,"1,024,405","267,090",40.899691,-73.854749
20631,173354054,01/06/2018,21:05:00,BRONX,47,0.0,MULTI DWELL - APT BUILD,False,18-24,M,WHITE HISPANIC,18-24,M,BLACK HISPANIC,"1,024,405","267,090",40.899691,-73.854749
20632,173354054,01/06/2018,21:05:00,BRONX,47,0.0,MULTI DWELL - APT BUILD,True,18-24,M,WHITE HISPANIC,18-24,M,BLACK HISPANIC,"1,024,405","267,090",40.899691,-73.854749
20633,173354054,01/06/2018,21:05:00,BRONX,47,0.0,MULTI DWELL - APT BUILD,False,18-24,M,BLACK,45-64,F,WHITE HISPANIC,"1,024,405","267,090",40.899691,-73.854749
20634,173354054,01/06/2018,21:05:00,BRONX,47,0.0,MULTI DWELL - APT BUILD,True,18-24,M,BLACK,45-64,F,WHITE HISPANIC,"1,024,405","267,090",40.899691,-73.854749
20635,173354054,01/06/2018,21:05:00,BRONX,47,0.0,MULTI DWELL - APT BUILD,False,18-24,M,WHITE HISPANIC,45-64,F,WHITE HISPANIC,"1,024,405","267,090",40.899691,-73.854749
20636,173354054,01/06/2018,21:05:00,BRONX,47,0.0,MULTI DWELL - APT BUILD,True,18-24,M,WHITE HISPANIC,45-64,F,WHITE HISPANIC,"1,024,405","267,090",40.899691,-73.854749
20637,173354054,01/06/2018,21:05:00,BRONX,47,0.0,MULTI DWELL - APT BUILD,False,18-24,M,BLACK,45-64,M,WHITE HISPANIC,"1,024,405","267,090",40.899691,-73.854749
20638,173354054,01/06/2018,21:05:00,BRONX,47,0.0,MULTI DWELL - APT BUILD,True,18-24,M,BLACK,45-64,M,WHITE HISPANIC,"1,024,405","267,090",40.899691,-73.854749
20639,173354054,01/06/2018,21:05:00,BRONX,47,0.0,MULTI DWELL - APT BUILD,False,18-24,M,WHITE HISPANIC,45-64,M,WHITE HISPANIC,"1,024,405","267,090",40.899691,-73.854749
20640,173354054,01/06/2018,21:05:00,BRONX,47,0.0,MULTI DWELL - APT BUILD,True,18-24,M,WHITE HISPANIC,45-64,M,WHITE HISPANIC,"1,024,405","267,090",40.899691,-73.854749
20641,173354054,01/06/2018,21:05:00,BRONX,47,0.0,MULTI DWELL - APT BUILD,False,25-44,M,BLACK,18-24,M,BLACK HISPANIC,"1,024,405","267,090",40.899691,-73.854749
20642,173354054,01/06/2018,21:05:00,BRONX,47,0.0,MULTI DWELL - APT BUILD,True,25-44,M,BLACK,18-24,M,BLACK HISPANIC,"1,024,405","267,090",40.899691,-73.854749
20643,173354054,01/06/2018,21:05:00,BRONX,47,0.0,MULTI DWELL - APT BUILD,False,25-44,M,BLACK,45-64,F,WHITE HISPANIC,"1,024,405","267,090",40.899691,-73.854749
20644,173354054,01/06/2018,21:05:00,BRONX,47,0.0,MULTI DWELL - APT BUILD,True,25-44,M,BLACK,45-64,F,WHITE HISPANIC,"1,024,405","267,090",40.899691,-73.854749
20645,173354054,01/06/2018,21:05:00,BRONX,47,0.0,MULTI DWELL - APT BUILD,False,25-44,M,BLACK,45-64,M,WHITE HISPANIC,"1,024,405","267,090",40.899691,-73.854749
20646,173354054,01/06/2018,21:05:00,BRONX,47,0.0,MULTI DWELL - APT BUILD,True,25-44,M,BLACK,45-64,M,WHITE HISPANIC,"1,024,405","267,090",40.899691,-73.854749
20647,173354055,01/06/2018,19:56:00,MANHATTAN,24,2.0,MULTI DWELL - PUBLIC HOUS,False,NaN,NaN,NaN,18-24,M,BLACK,"993,870","230,203",40.798533,-73.965256
20648,173961271,01/06/2018,3:30:00,BRONX,40,0.0,NaN,False,NaN,NaN,NaN,25-44,M,BLACK,"1,011,026","236,434",40.815600,-73.903267
20649,173354353,01/05/2018,23:31:00,BROOKLYN,77,0.0,GROCERY/BODEGA,False,25-44,M,BLACK,45-64,M,ASIAN / PACIFIC ISLANDER,"1,002,717","184,787",40.673863,-73.933427
20650,173247368,01/03/2018,21:44:00,BRONX,43,0.0,GROCERY/BODEGA,False,25-44,M,BLACK,25-44,M,BLACK HISPANIC,"1,020,861","242,240",40.831501,-73.867705
20651,173247367,01/03/2018,18:33:00,BRONX,44,0.0,MULTI DWELL - APT BUILD,False,18-24,M,BLACK HISPANIC,25-44,M,BLACK HISPANIC,"1,005,507","241,210",40.828724,-73.923191
20652,173220452,01/03/2018,14:41:00,BRONX,42,2.0,MULTI DWELL - PUBLIC HOUS,False,18-24,M,BLACK,18-24,F,BLACK,"1,011,047","239,814",40.824877,-73.903178
20653,173200546,01/03/2018,3:55:00,STATEN ISLAND,123,0.0,NaN,False,25-44,M,BLACK HISPANIC,18-24,M,WHITE HISPANIC,"920,515","138,386",40.546292,-74.229330
20654,173154491,01/01/2018,20:00:00,QUEENS,103,0.0,NaN,False,NaN,NaN,NaN,25-44,M,WHITE,"1,037,506","195,011",40.701785,-73.807931
20655,173135654,01/01/2018,6:30:00,BROOKLYN,70,0.0,BAR/NIGHT CLUB,False,NaN,NaN,NaN,18-24,M,BLACK,"996,108","176,259",40.650467,-73.957268
20656,173135654,01/01/2018,6:30:00,BROOKLYN,70,0.0,BAR/NIGHT CLUB,False,NaN,NaN,NaN,25-44,M,BLACK,"996,108","176,259",40.650467,-73.957268
20657,173132280,01/01/2018,1:30:00,BROOKLYN,73,0.0,NaN,False,NaN,NaN,NaN,25-44,M,BLACK,"1,009,357","177,370",40.653489,-73.909517
20658,173154856,01/01/2018,0:15:00,BRONX,40,0.0,NaN,False,NaN,NaN,NaN,25-44,M,BLACK,"1,005,432","233,240",40.806849,-73.923487

In [4]:
# Drop unneccessary columns
shoot_df =  shootings_df.drop(['PRECINCT', 'JURISDICTION_CODE', 
                               'LOCATION_DESC','STATISTICAL_MURDER_FLAG',
                              'PERP_AGE_GROUP','VIC_AGE_GROUP','X_COORD_CD','Y_COORD_CD'], axis=1)

# >>> values = {'A': 0, 'B': 1, 'C': 2, 'D': 3}
# >>> df.fillna(value=values)


shoot_df.fillna(value = {'PERP_SEX':'U','PERP_RACE':'UNKNOWN'}, inplace = True)
shoot_df


shoot_df['DATE'] = pd.to_datetime(shoot_df['OCCUR_DATE'], infer_datetime_format=True)

shoot_df

,INCIDENT_KEY,OCCUR_DATE,OCCUR_TIME,BORO,PERP_SEX,PERP_RACE,VIC_SEX,VIC_RACE,Latitude,Longitude,DATE
0,169180023,09/09/2017,3:57:00,STATEN ISLAND,U,UNKNOWN,M,BLACK,40.638126,-74.087467,2017-09-09
1,169180027,09/09/2017,22:15:00,BRONX,U,UNKNOWN,M,BLACK HISPANIC,40.869061,-73.902242,2017-09-09
2,169180025,09/09/2017,18:35:00,BROOKLYN,U,UNKNOWN,M,BLACK,40.696450,-73.943607,2017-09-09
3,169180024,09/09/2017,15:20:00,BROOKLYN,M,BLACK,M,BLACK,40.639137,-73.951236,2017-09-09
4,169180022,09/09/2017,0:20:00,BROOKLYN,U,UNKNOWN,M,ASIAN / PACIFIC ISLANDER,40.596134,-73.939619,2017-09-09
5,156603440,09/09/2016,20:58:00,BROOKLYN,M,BLACK,M,BLACK,40.650929,-73.930297,2016-09-09
6,156603439,09/09/2016,20:43:00,BRONX,U,UNKNOWN,M,WHITE HISPANIC,40.814103,-73.902027,2016-09-09
7,156603438,09/09/2016,11:50:00,MANHATTAN,U,UNKNOWN,M,BLACK,40.824538,-73.937081,2016-09-09
8,156552658,09/09/2016,0:18:00,QUEENS,U,UNKNOWN,M,BLACK,40.670030,-73.783113,2016-09-09
9,146014287,09/09/2015,23:08:00,BRONX,U,UNKNOWN,M,BLACK,40.883658,-73.847848,2015-09-09
10,146014286,09/09/2015,23:00:00,MANHATTAN,U,UNKNOWN,M,BLACK,40.802707,-73.949188,2015-09-09
11,146013532,09/09/2015,19:03:00,BROOKLYN,M,BLACK,M,BLACK,40.674459,-73.938910,2015-09-09
12,145992814,09/09/2015,11:54:00,BROOKLYN,M,WHITE HISPANIC,M,WHITE HISPANIC,40.626383,-73.961621,2015-09-09
13,138627598,09/09/2014,17:36:00,BROOKLYN,U,UNKNOWN,M,BLACK,40.666411,-73.919485,2014-09-09
14,92525610,09/09/2013,5:26:00,BROOKLYN,U,UNKNOWN,M,BLACK,40.656952,-73.887239,2013-09-09
15,92507649,09/09/2013,4:35:00,BROOKLYN,U,UNKNOWN,M,BLACK,40.693333,-73.960003,2013-09-09
16,92507648,09/09/2013,3:55:00,MANHATTAN,M,BLACK,M,BLACK,40.754916,-73.972476,2013-09-09
17,92525805,09/09/2013,15:14:00,QUEENS,M,BLACK,M,BLACK,40.686328,-73.759450,2013-09-09
18,86650273,09/09/2012,2:15:00,QUEENS,U,UNKNOWN,M,BLACK,40.690203,-73.757485,2012-09-09
19,86650272,09/09/2012,2:01:00,MANHATTAN,U,UNKNOWN,M,BLACK,40.798146,-73.950358,2012-09-09
20,86664788,09/09/2012,23:22:00,STATEN ISLAND,M,BLACK,M,BLACK,40.636525,-74.116231,2012-09-09
21,86651100,09/09/2012,15:47:00,BROOKLYN,U,UNKNOWN,M,BLACK,40.677659,-73.949773,2012-09-09
22,80667853,09/09/2011,23:00:00,BRONX,M,BLACK,F,BLACK,40.841944,-73.914249,2011-09-09
23,80667853,09/09/2011,23:00:00,BRONX,M,WHITE HISPANIC,F,BLACK,40.841944,-73.914249,2011-09-09
24,80667853,09/09/2011,23:00:00,BRONX,M,BLACK,M,BLACK,40.841944,-73.914249,2011-09-09
25,80667853,09/09/2011,23:00:00,BRONX,M,WHITE HISPANIC,M,BLACK,40.841944,-73.914249,2011-09-09
26,80667641,09/09/2011,22:43:00,QUEENS,M,BLACK HISPANIC,M,WHITE HISPANIC,40.704445,-73.911973,2011-09-09
27,80667641,09/09/2011,22:43:00,QUEENS,M,BLACK HISPANIC,M,WHITE HISPANIC,40.704445,-73.911973,2011-09-09
28,80655008,09/09/2011,13:32:00,BROOKLYN,U,UNKNOWN,M,BLACK,40.652409,-73.954337,2011-09-09
29,80654704,09/09/2011,12:39:00,QUEENS,M,BLACK,M,BLACK,40.757105,-73.908048,2011-09-09
...,...,...,...,...,...,...,...,...,...,...,...
20629,173354054,01/06/2018,21:05:00,BRONX,M,BLACK,M,BLACK HISPANIC,40.899691,-73.854749,2018-01-06
20630,173354054,01/06/2018,21:05:00,BRONX,M,BLACK,M,BLACK HISPANIC,40.899691,-73.854749,2018-01-06
20631,173354054,01/06/2018,21:05:00,BRONX,M,WHITE HISPANIC,M,BLACK HISPANIC,40.899691,-73.854749,2018-01-06
20632,173354054,01/06/2018,21:05:00,BRONX,M,WHITE HISPANIC,M,BLACK HISPANIC,40.899691,-73.854749,2018-01-06
20633,173354054,01/06/2018,21:05:00,BRONX,M,BLACK,F,WHITE HISPANIC,40.899691,-73.854749,2018-01-06
20634,173354054,01/06/2018,21:05:00,BRONX,M,BLACK,F,WHITE HISPANIC,40.899691,-73.854749,2018-01-06
20635,173354054,01/06/2018,21:05:00,BRONX,M,WHITE HISPANIC,F,WHITE HISPANIC,40.899691,-73.854749,2018-01-06
20636,173354054,01/06/2018,21:05:00,BRONX,M,WHITE HISPANIC,F,WHITE HISPANIC,40.899691,-73.854749,2018-01-06
20637,173354054,01/06/2018,21:05:00,BRONX,M,BLACK,M,WHITE HISPANIC,40.899691,-73.854749,2018-01-06
20638,173354054,01/06/2018,21:05:00,BRONX,M,BLACK,M,WHITE HISPANIC,40.899691,-73.854749,2018-01-06
20639,173354054,01/06/2018,21:05:00,BRONX,M,WHITE HISPANIC,M,WHITE HISPANIC,40.899691,-73.854749,2018-01-06
20640,173354054,01/06/2018,21:05:00,BRONX,M,WHITE HISPANIC,M,WHITE HISPANIC,40.899691,-73.854749,2018-01-06
20641,173354054,01/06/2018,21:05:00,BRONX,M,BLACK,M,BLACK HISPANIC,40.899691,-73.854749,2018-01-06
20642,173354054,01/06/2018,21:05:00,BRONX,M,BLACK,M,BLACK HISPANIC,40.899691,-73.854749,2018-01-06
20643,173354054,01/06/2018,21:05:00,BRONX,M,BLACK,F,WHITE HISPANIC,40.899691,-73.854749,2018-01-06
20644,173354054,01/06/2018,21:05:00,BRONX,M,BLACK,F,WHITE HISPANIC,40.899691,-73.854749,2018-01-06
20645,173354054,01/06/2018,21:05:00,BRONX,M,BLACK,M,WHITE HISPANIC,40.899691,-73.854749,2018-01-06
20646,173354054,01/06/2018,21:05:00,BRONX,M,BLACK,M,WHITE HISPANIC,40.899691,-73.854749,2018-01-06
20647,173354055,01/06/2018,19:56:00,MANHATTAN,U,UNKNOWN,M,BLACK,40.798533,-73.965256,2018-01-06
20648,173961271,01/06/2018,3:30:00,BRONX,U,UNKNOWN,M,BLACK,40.815600,-73.903267,2018-01-06
20649,173354353,01/05/2018,23:31:00,BROOKLYN,M,BLACK,M,ASIAN / PACIFIC ISLANDER,40.673863,-73.933427,2018-01-05
20650,173247368,01/03/2018,21:44:00,BRONX,M,BLACK,M,BLACK HISPANIC,40.831501,-73.867705,2018-01-03
20651,173247367,01/03/2018,18:33:00,BRONX,M,BLACK HISPANIC,M,BLACK HISPANIC,40.828724,-73.923191,2018-01-03
20652,173220452,01/03/2018,14:41:00,BRONX,M,BLACK,F,BLACK,40.824877,-73.903178,2018-01-03
20653,173200546,01/03/2018,3:55:00,STATEN ISLAND,M,BLACK HISPANIC,M,WHITE HISPANIC,40.546292,-74.229330,2018-01-03
20654,173154491,01/01/2018,20:00:00,QUEENS,U,UNKNOWN,M,WHITE,40.701785,-73.807931,2018-01-01
20655,173135654,01/01/2018,6:30:00,BROOKLYN,U,UNKNOWN,M,BLACK,40.650467,-73.957268,2018-01-01
20656,173135654,01/01/2018,6:30:00,BROOKLYN,U,UNKNOWN,M,BLACK,40.650467,-73.957268,2018-01-01
20657,173132280,01/01/2018,1:30:00,BROOKLYN,U,UNKNOWN,M,BLACK,40.653489,-73.909517,2018-01-01
20658,173154856,01/01/2018,0:15:00,BRONX,U,UNKNOWN,M,BLACK,40.806849,-73.923487,2018-01-01

In [5]:
cnx = sqlite3.connect('db/db.sqlite')
cur = cnx.cursor()
cur.execute('drop table if exists table_name')
cur.execute('drop table if exists Shootings')

# DROP TABLE [IF EXISTS] [schema_name.]table_name;
shoot_df.to_sql('Shootings', cnx)

In [6]:
cur = cnx.cursor()
cur.execute("select * from Shootings limit 5;")

In [7]:
results = cur.fetchall()
print(results)

[(0, 169180023, '09/09/2017', '3:57:00', 'STATEN ISLAND', 'U', 'UNKNOWN', 'M', 'BLACK', 40.63812599100004, -74.08746692099999, '2017-09-09 00:00:00'), (1, 169180027, '09/09/2017', '22:15:00', 'BRONX', 'U', 'UNKNOWN', 'M', 'BLACK HISPANIC', 40.869060690000026, -73.90224225899993, '2017-09-09 00:00:00'), (2, 169180025, '09/09/2017', '18:35:00', 'BROOKLYN', 'U', 'UNKNOWN', 'M', 'BLACK', 40.69645001400005, -73.94360673699998, '2017-09-09 00:00:00'), (3, 169180024, '09/09/2017', '15:20:00', 'BROOKLYN', 'M', 'BLACK', 'M', 'BLACK', 40.63913704300006, -73.951236227, '2017-09-09 00:00:00'), (4, 169180022, '09/09/2017', '0:20:00', 'BROOKLYN', 'U', 'UNKNOWN', 'M', 'ASIAN / PACIFIC ISLANDER', 40.59613433800007, -73.93961890199995, '2017-09-09 00:00:00')]

In [8]:
shoot_df.to_csv("shoot_df.csv")

In [78]:
file_two = "weather_dft.csv"

In [79]:
w_df = pd.read_csv(file_two, encoding="ISO-8859-1")
w_df.drop(['Unnamed: 0'],axis = 1, inplace = True)

In [87]:
w_df['DATE'] = pd.to_datetime(w_df['date'], infer_datetime_format=True)
w_df.head()

        date  Farenheit  clouds_all weather_description       DATE
0  10/1/2012  59.820909          20          few clouds 2012-10-01
1  10/2/2012  63.952083          20          few clouds 2012-10-02
2  10/3/2012  62.833947          75       broken clouds 2012-10-03
3  10/4/2012  65.203556         100                mist 2012-10-04
4  10/5/2012  69.797872          91                mist 2012-10-05

In [83]:
shoot_df_m = shoot_df[["DATE","VIC_RACE"]]
shoot_df_m['count']=np.ones([shoot_df_m.shape[0],1])
shoot_df_m.head()

C:\Users\Quake\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

        DATE                  VIC_RACE  count
0 2017-09-09                     BLACK    1.0
1 2017-09-09            BLACK HISPANIC    1.0
2 2017-09-09                     BLACK    1.0
3 2017-09-09                     BLACK    1.0
4 2017-09-09  ASIAN / PACIFIC ISLANDER    1.0

In [84]:
shoot_df_m.agg({'DATE':'min','VIC_RACE':'min','count':'sum'})

DATE                   2006-01-01 00:00:00
VIC_RACE    AMERICAN INDIAN/ALASKAN NATIVE
count                                20659
dtype: object

In [85]:
a = shoot_df_m.groupby(['DATE','VIC_RACE']).count()
b = a.reset_index()
b.head()

        DATE        VIC_RACE  count
0 2006-01-01           BLACK      7
1 2006-01-01  WHITE HISPANIC      1
2 2006-01-02           BLACK      3
3 2006-01-02  BLACK HISPANIC      1
4 2006-01-03           BLACK      3

In [89]:
weathershootings = w_df.merge(b,left_on='DATE',right_on='DATE')
weathershootings

,date,Farenheit,clouds_all,weather_description,DATE,VIC_RACE,count
0,10/1/2012,59.820909,20,few clouds,2012-10-01,BLACK,1
1,10/1/2012,59.820909,20,few clouds,2012-10-01,WHITE HISPANIC,2
2,10/2/2012,63.952083,20,few clouds,2012-10-02,BLACK,7
3,10/3/2012,62.833947,75,broken clouds,2012-10-03,WHITE HISPANIC,2
4,10/4/2012,65.203556,100,mist,2012-10-04,BLACK,6
5,10/6/2012,66.837667,85,mist,2012-10-06,WHITE HISPANIC,6
6,10/7/2012,65.518889,20,few clouds,2012-10-07,BLACK,3
7,10/7/2012,65.518889,20,few clouds,2012-10-07,BLACK HISPANIC,1
8,10/7/2012,65.518889,20,few clouds,2012-10-07,WHITE HISPANIC,1
9,10/8/2012,50.952308,1,sky is clear,2012-10-08,BLACK,2
10,10/9/2012,47.648788,100,moderate rain,2012-10-09,BLACK,3
11,10/10/2012,53.541786,90,overcast clouds,2012-10-10,BLACK,2
12,10/12/2012,53.752917,20,few clouds,2012-10-12,BLACK,3
13,10/13/2012,50.075833,0,sky is Clear,2012-10-13,BLACK,7
14,10/13/2012,50.075833,0,sky is Clear,2012-10-13,WHITE HISPANIC,1
15,10/14/2012,43.733750,1,sky is clear,2012-10-14,BLACK,5
16,10/14/2012,43.733750,1,sky is clear,2012-10-14,BLACK HISPANIC,3
17,10/14/2012,43.733750,1,sky is clear,2012-10-14,WHITE HISPANIC,3
18,10/15/2012,57.441667,75,broken clouds,2012-10-15,BLACK,2
19,10/15/2012,57.441667,75,broken clouds,2012-10-15,BLACK HISPANIC,1
20,10/15/2012,57.441667,75,broken clouds,2012-10-15,WHITE HISPANIC,1
21,10/16/2012,64.970294,40,scattered clouds,2012-10-16,BLACK,1
22,10/16/2012,64.970294,40,scattered clouds,2012-10-16,BLACK HISPANIC,1
23,10/17/2012,56.267600,93,light rain,2012-10-17,BLACK,2
24,10/18/2012,49.167083,20,few clouds,2012-10-18,BLACK,1
25,10/19/2012,52.750417,75,broken clouds,2012-10-19,BLACK,1
26,10/19/2012,52.750417,75,broken clouds,2012-10-19,WHITE HISPANIC,1
27,10/20/2012,64.201277,90,overcast clouds,2012-10-20,BLACK,2
28,10/20/2012,64.201277,90,overcast clouds,2012-10-20,WHITE HISPANIC,1
29,10/21/2012,61.240000,10,mist,2012-10-21,BLACK,2
...,...,...,...,...,...,...,...
3333,12/8/2018,28.254800,1,sky is clear,2018-12-08,BLACK,3
3334,12/8/2018,28.254800,1,sky is clear,2018-12-08,UNKNOWN,2
3335,12/8/2018,28.254800,1,sky is clear,2018-12-08,WHITE HISPANIC,1
3336,12/9/2018,28.981250,40,scattered clouds,2018-12-09,BLACK,1
3337,12/9/2018,28.981250,40,scattered clouds,2018-12-09,WHITE,1
3338,12/10/2018,31.027500,90,overcast clouds,2018-12-10,BLACK,2
3339,12/11/2018,30.903333,20,few clouds,2018-12-11,BLACK,2
3340,12/12/2018,34.731667,20,few clouds,2018-12-12,BLACK,2
3341,12/14/2018,42.056897,90,light rain,2018-12-14,WHITE HISPANIC,1
3342,12/15/2018,47.535455,90,light rain,2018-12-15,BLACK,2
3343,12/15/2018,47.535455,90,light rain,2018-12-15,BLACK HISPANIC,3
3344,12/15/2018,47.535455,90,light rain,2018-12-15,WHITE HISPANIC,1
3345,12/16/2018,41.596000,90,overcast clouds,2018-12-16,WHITE HISPANIC,3
3346,12/18/2018,36.457917,90,overcast clouds,2018-12-18,BLACK,2
3347,12/20/2018,38.067333,1,sky is clear,2018-12-20,BLACK,2
3348,12/20/2018,38.067333,1,sky is clear,2018-12-20,WHITE HISPANIC,1
3349,12/21/2018,53.744211,90,moderate rain,2018-12-21,BLACK,2
3350,12/22/2018,48.858214,90,mist,2018-12-22,BLACK,4
3351,12/23/2018,40.220833,75,broken clouds,2018-12-23,BLACK,1
3352,12/23/2018,40.220833,75,broken clouds,2018-12-23,BLACK HISPANIC,1
3353,12/24/2018,37.680000,40,scattered clouds,2018-12-24,WHITE HISPANIC,1
3354,12/25/2018,36.737917,75,broken clouds,2018-12-25,BLACK,1
3355,12/26/2018,36.108333,75,broken clouds,2018-12-26,BLACK,2
3356,12/26/2018,36.108333,75,broken clouds,2018-12-26,WHITE HISPANIC,1
3357,12/28/2018,47.924348,40,scattered clouds,2018-12-28,BLACK,3
3358,12/28/2018,47.924348,40,scattered clouds,2018-12-28,UNKNOWN,1
3359,12/28/2018,47.924348,40,scattered clouds,2018-12-28,WHITE HISPANIC,1
3360,12/30/2018,38.056667,40,scattered clouds,2018-12-30,BLACK,3
3361,12/31/2018,37.974483,75,broken clouds,2018-12-31,BLACK,1
3362,12/31/2018,37.974483,75,broken clouds,2018-12-31,WHITE,1

In [90]:
weathershootings.to_csv("weathershootings.csv")