In [13]:
import pytemperature
import pandas as pd
import os
import csv
import time
import datetime

In [14]:
file = "Resources/ny hourly weather.csv"
weather_df = pd.read_csv(file)
weather_df.head()

,dt,date,city_id,Farenheit,temp_min,temp_max,pressure,sea_level,grnd_level,humidity,wind_speed,wind_deg,rain_1h,snow_1h,snow_3h,clouds_all,weather_id,weather_main,weather_description,weather_icon
0,1349096400,2012-10-01,5128581,59.13,286.150000,294.260000,1012,NaN,NaN,58,7,260,NaN,NaN,NaN,20,801,Clouds,few clouds,02d
1,1349100000,2012-10-01,5128581,59.26,288.297219,288.297219,1012,NaN,NaN,57,7,260,NaN,NaN,NaN,20,801,Clouds,few clouds,2
2,1349103600,2012-10-01,5128581,59.40,288.374375,288.374375,1012,NaN,NaN,57,7,260,NaN,NaN,NaN,20,801,Clouds,few clouds,2
3,1349107200,2012-10-01,5128581,59.54,288.451594,288.451594,1012,NaN,NaN,57,7,261,NaN,NaN,NaN,20,801,Clouds,few clouds,2
4,1349110800,2012-10-01,5128581,59.68,288.528813,288.528813,1012,NaN,NaN,56,6,261,NaN,NaN,NaN,20,801,Clouds,few clouds,2

In [15]:
weather_df = weather_df.groupby('date', as_index=False, sort=False).agg({'Farenheit':'mean', 'clouds_all':'first','weather_description':'first'}).reindex_axis(['date','Farenheit','clouds_all','weather_description'], axis=1)
print(weather_df)

            date  Farenheit  clouds_all weather_description
0     2012-10-01  59.820909          20          few clouds
1     2012-10-02  63.952083          20          few clouds
2     2012-10-03  62.833947          75       broken clouds
3     2012-10-04  65.203556         100                mist
4     2012-10-05  69.797872          91                mist
5     2012-10-06  66.837667          85                mist
6     2012-10-07  65.518889          20          few clouds
7     2012-10-08  50.952308           1        sky is clear
8     2012-10-09  47.648788         100       moderate rain
9     2012-10-10  53.541786          90     overcast clouds
10    2012-10-11  56.965385          96        sky is clear
11    2012-10-12  53.752917          20          few clouds
12    2012-13-10  50.075833           0        sky is Clear
13    2012-14-10  43.733750           1        sky is clear
14    2012-15-10  57.441667          75       broken clouds
15    2012-16-10  64.970294          40    scattered clouds
16    2012-17-10  56.267600          93          light rain
17    2012-18-10  49.167083          20          few clouds
18    2012-19-10  52.750417          75       broken clouds
19    2012-20-10  64.201277          90     overcast clouds
20    2012-21-10  61.240000          10                mist
21    2012-22-10  55.772500          30    scattered clouds
22    2012-23-10  56.933750           1        sky is clear
23    2012-24-10  55.782000           1        sky is clear
24    2012-25-10  57.505641          90     overcast clouds
25    2012-26-10  58.181250          90                mist
26    2012-27-10  60.691667          90                haze
27    2012-28-10  62.258148          90     overcast clouds
28    2012-29-10  57.775000          75       broken clouds
29    2012-30-10  56.997674          90     overcast clouds
...          ...        ...         ...                 ...
2577  2019-22-10  56.843158           1           clear sky
2578  2019-23-10  60.281667          90       moderate rain
2579  2019-24-10  54.910000           1           clear sky
2580  2019-25-10  54.798333           1           clear sky
2581  2019-26-10  57.601250           1           clear sky
2582  2019-27-10  59.817778          75          light rain
2583  2019-28-10  57.942400          40                mist
2584  2019-29-10  56.575849          90     overcast clouds
2585  2019-30-10  59.469091          90          light rain
2586  2019-31-10  63.954464          90                mist
2587  2019-11-01  56.355185          90          light rain
2588  2019-11-02  43.925417           1           clear sky
2589  2019-11-03  45.516250          90     overcast clouds
2590  2019-11-04  44.864167           1           clear sky
2591  2019-11-05  52.347083           1           clear sky
2592  2019-11-06  49.137083           1           clear sky
2593  2019-11-07  46.948000           1             squalls
2594  2019-11-08  38.672400          90          light rain
2595  2019-11-09  31.161250           1           clear sky
2596  2019-11-10  38.883333          75       broken clouds
2597  2019-11-11  47.456250          20          few clouds
2598  2019-11-12  44.846250           1           clear sky
2599  2019-13-11  27.071250          20          few clouds
2600  2019-14-11  31.237083           1           clear sky
2601  2019-15-11  39.751667           1          light rain
2602  2019-16-11  37.810417           1           clear sky
2603  2019-17-11  34.050000           1           clear sky
2604  2019-18-11  38.805333          90     overcast clouds
2605  2019-19-11  41.442000          90          light rain
2606  2019-20-11  42.210000          75       broken clouds

[2607 rows x 4 columns]

C:\Users\new\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: '.reindex_axis' is deprecated and will be removed in a future version. Use '.reindex' instead.
  """Entry point for launching an IPython kernel.

In [16]:
weather_df

            date  Farenheit  clouds_all weather_description
0     2012-10-01  59.820909          20          few clouds
1     2012-10-02  63.952083          20          few clouds
2     2012-10-03  62.833947          75       broken clouds
3     2012-10-04  65.203556         100                mist
4     2012-10-05  69.797872          91                mist
5     2012-10-06  66.837667          85                mist
6     2012-10-07  65.518889          20          few clouds
7     2012-10-08  50.952308           1        sky is clear
8     2012-10-09  47.648788         100       moderate rain
9     2012-10-10  53.541786          90     overcast clouds
10    2012-10-11  56.965385          96        sky is clear
11    2012-10-12  53.752917          20          few clouds
12    2012-13-10  50.075833           0        sky is Clear
13    2012-14-10  43.733750           1        sky is clear
14    2012-15-10  57.441667          75       broken clouds
15    2012-16-10  64.970294          40    scattered clouds
16    2012-17-10  56.267600          93          light rain
17    2012-18-10  49.167083          20          few clouds
18    2012-19-10  52.750417          75       broken clouds
19    2012-20-10  64.201277          90     overcast clouds
20    2012-21-10  61.240000          10                mist
21    2012-22-10  55.772500          30    scattered clouds
22    2012-23-10  56.933750           1        sky is clear
23    2012-24-10  55.782000           1        sky is clear
24    2012-25-10  57.505641          90     overcast clouds
25    2012-26-10  58.181250          90                mist
26    2012-27-10  60.691667          90                haze
27    2012-28-10  62.258148          90     overcast clouds
28    2012-29-10  57.775000          75       broken clouds
29    2012-30-10  56.997674          90     overcast clouds
...          ...        ...         ...                 ...
2577  2019-22-10  56.843158           1           clear sky
2578  2019-23-10  60.281667          90       moderate rain
2579  2019-24-10  54.910000           1           clear sky
2580  2019-25-10  54.798333           1           clear sky
2581  2019-26-10  57.601250           1           clear sky
2582  2019-27-10  59.817778          75          light rain
2583  2019-28-10  57.942400          40                mist
2584  2019-29-10  56.575849          90     overcast clouds
2585  2019-30-10  59.469091          90          light rain
2586  2019-31-10  63.954464          90                mist
2587  2019-11-01  56.355185          90          light rain
2588  2019-11-02  43.925417           1           clear sky
2589  2019-11-03  45.516250          90     overcast clouds
2590  2019-11-04  44.864167           1           clear sky
2591  2019-11-05  52.347083           1           clear sky
2592  2019-11-06  49.137083           1           clear sky
2593  2019-11-07  46.948000           1             squalls
2594  2019-11-08  38.672400          90          light rain
2595  2019-11-09  31.161250           1           clear sky
2596  2019-11-10  38.883333          75       broken clouds
2597  2019-11-11  47.456250          20          few clouds
2598  2019-11-12  44.846250           1           clear sky
2599  2019-13-11  27.071250          20          few clouds
2600  2019-14-11  31.237083           1           clear sky
2601  2019-15-11  39.751667           1          light rain
2602  2019-16-11  37.810417           1           clear sky
2603  2019-17-11  34.050000           1           clear sky
2604  2019-18-11  38.805333          90     overcast clouds
2605  2019-19-11  41.442000          90          light rain
2606  2019-20-11  42.210000          75       broken clouds

[2607 rows x 4 columns]

In [17]:
weather_df.to_csv("weather_df.csv")