In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
shooting_incident = "Major Holiday Shootings.csv"

In [4]:
shooting_incident_df = pd.read_csv(shooting_incident)

In [5]:
shooting_incident_df.head

<bound method NDFrame.head of         Date        Holiday  Incident Count  Unnamed: 3  Unnamed: 4  \
0     1/1/06  New Years Day               8         NaN         NaN
1     1/1/07  New Years Day              18         NaN         NaN
2     1/1/08  New Years Day              19         NaN         NaN
3     1/1/09  New Years Day               7         NaN         NaN
4     1/1/10  New Years Day               8         NaN         NaN
..       ...            ...             ...         ...         ...
73  12/25/14      Christmas               6         NaN         NaN
74  12/25/15      Christmas               6         NaN         NaN
75  12/25/16      Christmas               3         NaN         NaN
76  12/25/17      Christmas               7         NaN         NaN
77  12/25/18      Christmas               1         NaN         NaN

    Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  Unnamed: 10  \
0          NaN         NaN         NaN         NaN         NaN          NaN
1          NaN         NaN         NaN         NaN         NaN          NaN
2          NaN         NaN         NaN         NaN         NaN          NaN
3          NaN         NaN         NaN         NaN         NaN          NaN
4          NaN         NaN         NaN         NaN         NaN          NaN
..         ...         ...         ...         ...         ...          ...
73         NaN         NaN         NaN         NaN         NaN          NaN
74         NaN         NaN         NaN         NaN         NaN          NaN
75         NaN         NaN         NaN         NaN         NaN          NaN
76         NaN         NaN         NaN         NaN         NaN          NaN
77         NaN         NaN         NaN         NaN         NaN          NaN

    Unnamed: 11  Unnamed: 12  Unnamed: 13  Unnamed: 14  Unnamed: 15  \
0           NaN          NaN          NaN          NaN          NaN
1           NaN          NaN          NaN          NaN          NaN
2           NaN          NaN          NaN          NaN          NaN
3           NaN          NaN          NaN          NaN          NaN
4           NaN          NaN          NaN          NaN          NaN
..          ...          ...          ...          ...          ...
73          NaN          NaN          NaN          NaN          NaN
74          NaN          NaN          NaN          NaN          NaN
75          NaN          NaN          NaN          NaN          NaN
76          NaN          NaN          NaN          NaN          NaN
77          NaN          NaN          NaN          NaN          NaN

    Unnamed: 16  Unnamed: 17
0           NaN          NaN
1           NaN          NaN
2           NaN          NaN
3           NaN          NaN
4           NaN          NaN
..          ...          ...
73          NaN          NaN
74          NaN          NaN
75          NaN          NaN
76          NaN          NaN
77          NaN          NaN

[78 rows x 18 columns]>

In [10]:
new_shooting_incident_df = shooting_incident_df[['Date', 'Holiday', 'Incident Count']].copy()
new_shooting_incident_df.head(60)

       Date           Holiday  Incident Count
0    1/1/06     New Years Day               8
1    1/1/07     New Years Day              18
2    1/1/08     New Years Day              19
3    1/1/09     New Years Day               7
4    1/1/10     New Years Day               8
5    1/1/11     New Years Day              12
6    1/1/12     New Years Day              11
7    1/1/13     New Years Day              11
8    1/1/14     New Years Day              12
9    1/1/15     New Years Day               3
10   1/1/16     New Years Day               7
11   1/1/17     New Years Day               7
12   1/1/18     New Years Day               5
13   4/4/06  Independence Day               3
14   4/4/07  Independence Day               5
15   4/4/08  Independence Day               0
16   4/4/09  Independence Day               7
17   4/4/10  Independence Day               8
18   4/4/11  Independence Day               1
19   4/4/12  Independence Day               5
20   4/4/13  Independence Day               2
21   4/4/14  Independence Day               0
22   4/4/15  Independence Day               2
23   4/4/16  Independence Day               2
24   4/4/17  Independence Day               4
25   4/4/18  Independence Day               1
26  5/29/06      Memorial Day              11
27  5/28/07      Memorial Day               6
28  5/26/08      Memorial Day              14
29  5/25/09      Memorial Day               8
30  5/31/10      Memorial Day              10
31  5/30/11      Memorial Day              13
32  5/28/12      Memorial Day               8
33  5/27/13      Memorial Day               6
34  5/26/14      Memorial Day               9
35  5/25/15      Memorial Day               6
36  5/30/16      Memorial Day               2
37  5/29/17      Memorial Day               1
38  5/28/18      Memorial Day              10
39  9/23/06     Thanksgiving                6
40  9/22/07     Thanksgiving                8
41  9/27/08     Thanksgiving               10
42  9/26/09     Thanksgiving               15
43  9/25/10     Thanksgiving                7
44  9/24/11     Thanksgiving               10
45  9/22/12     Thanksgiving               13
46  9/28/13     Thanksgiving                5
47  9/27/14     Thanksgiving                9
48  9/26/15     Thanksgiving               13
49  9/24/16     Thanksgiving                2
50  9/23/17     Thanksgiving                1
51  9/22/18     Thanksgiving                3
52  9/24/06      Black Friday               8
53  9/23/07      Black Friday               6
54  9/28/08      Black Friday              17
55  9/27/09      Black Friday              11
56  9/26/10      Black Friday               9
57  9/25/11      Black Friday              18
58  9/23/12      Black Friday               7
59  9/29/13      Black Friday               3